// Placeholder job-match data.
//
// There is no jobs/matching backend in this codebase yet (no table, no
// external job-board integration). This mock list exists purely so the
// Overview, Jobs, and Job Detail pages have something real-looking to
// render, matching the design handoff's own explicit framing ("placeholder
// data used -- replace with real"). Replace with a real data source once a
// jobs backend exists.

export const jobWorkModes = ["Remote", "Hybrid", "On-site"] as const;
export type JobWorkMode = (typeof jobWorkModes)[number];

export const jobTypes = ["Full-time", "Part-time", "Contract", "Internship"] as const;
export type JobType = (typeof jobTypes)[number];

export const experienceLevels = ["Entry", "Mid", "Senior"] as const;
export type ExperienceLevel = (typeof experienceLevels)[number];

export const companySizes = ["1-50", "51-200", "201-1000", "1000+"] as const;
export type CompanySize = (typeof companySizes)[number];

export type MockJob = {
  about: string;
  applyInDays: number;
  benefits: string[];
  company: string;
  companySize: CompanySize;
  experienceLevel: ExperienceLevel;
  industry: string;
  description: string;
  id: string;
  jobType: JobType;
  location: string;
  matchPercent: number;
  niceToHave: string[];
  posted: string;
  requirements: string[];
  responsibilities: string[];
  salaryMax: number;
  salaryMin: number;
  sponsorsVisa: boolean;
  team: string;
  tags: string[];
  title: string;
  workMode: JobWorkMode;
};

const featuredJobs: MockJob[] = [
  {
    about: "Nordstack runs one of Europe's larger online marketplaces, with ranking and search as its core product surface.",
    applyInDays: 21,
    benefits: ["Remote-first with a co-working allowance", "Home-office budget", "28 days of paid leave", "Company pension contribution"],
    team: "You'll join a 12-person ranking team of ML engineers, data scientists and backend engineers based in Berlin.",
    company: "Nordstack",
    companySize: "201-1000",
    description:
      "Nordstack builds the ranking systems behind a large European marketplace. You'll work on the models that decide what buyers see first.",
    experienceLevel: "Senior",
    id: "1",
    industry: "E-commerce",
    jobType: "Full-time",
    location: "Berlin, DE",
    matchPercent: 92,
    niceToHave: ["Experience with real-time inference", "Prior marketplace or e-commerce work"],
    posted: "a day ago",
    requirements: [
      "3+ years building and shipping ML models in production",
      "Strong Python skills and comfort with large data pipelines",
      "Experience explaining model behavior to non-technical stakeholders",
    ],
    responsibilities: [
      "Own the ranking pipeline for a high-traffic marketplace surface",
      "Design and run experiments to measure model impact",
      "Partner with backend engineers to keep inference latency low",
    ],
    salaryMax: 85000,
    salaryMin: 65000,
    sponsorsVisa: true,
    tags: ["Python", "ML pipelines", "PyTorch", "SQL"],
    title: "Machine Learning Engineer, Ranking",
    workMode: "Hybrid",
  },
  {
    about: "Voltiq builds software that schedules and balances electricity across regional grids.",
    applyInDays: 14,
    benefits: ["Hybrid schedule", "Learning budget", "Health and wellbeing allowance", "Team offsites twice a year"],
    team: "A remote-first platform team of 9 engineers spread across the Netherlands, Germany and Poland.",
    company: "Voltiq",
    companySize: "51-200",
    description:
      "Voltiq is a distributed-systems team building the platform that powers energy-grid scheduling across Europe.",
    experienceLevel: "Senior",
    id: "2",
    industry: "Energy",
    jobType: "Full-time",
    location: "Amsterdam, NL",
    matchPercent: 88,
    niceToHave: ["Experience with Kubernetes", "Background in energy or infrastructure systems"],
    posted: "6 days ago",
    requirements: [
      "Strong Go experience in a production, multi-service environment",
      "Comfortable reasoning about consistency and failure modes in distributed systems",
      "Experience owning services end-to-end, including on-call",
    ],
    responsibilities: [
      "Design and operate services on the core scheduling platform",
      "Improve reliability and observability across the platform",
      "Collaborate with product on new platform capabilities",
    ],
    salaryMax: 95000,
    salaryMin: 70000,
    sponsorsVisa: false,
    tags: ["Go", "Distributed systems", "Kubernetes", "PostgreSQL"],
    title: "Backend Engineer, Platform",
    workMode: "Remote",
  },
  {
    about: "Reef Labs makes collaboration tools for early-stage product teams.",
    applyInDays: 10,
    benefits: ["Relocation support", "30 days of paid leave", "Modern equipment of your choice", "Language course budget"],
    team: "A design team of four working closely with a small group of front-end engineers.",
    company: "Reef Labs",
    companySize: "1-50",
    description:
      "Reef Labs designs tools for early-stage product teams. This role owns the design system and growth-facing surfaces.",
    experienceLevel: "Mid",
    id: "3",
    industry: "Software",
    jobType: "Contract",
    location: "Remote, EU",
    matchPercent: 85,
    niceToHave: ["Front-end implementation skills", "Experience running user research"],
    posted: "3 days ago",
    requirements: [
      "A portfolio showing end-to-end product design work",
      "Strong command of Figma and modern design-system tooling",
      "Experience partnering closely with engineering",
    ],
    responsibilities: [
      "Own design system components used across the product",
      "Lead design for growth and onboarding surfaces",
      "Run lightweight research to validate design decisions",
    ],
    salaryMax: 78000,
    salaryMin: 58000,
    sponsorsVisa: true,
    tags: ["Figma", "Design systems", "Prototyping", "User research"],
    title: "Product Designer, Growth",
    workMode: "Remote",
  },
  {
    about: "Kestrel helps subscription businesses understand and retain their customers.",
    applyInDays: 18,
    benefits: ["30 days of paid leave", "Learning budget of EUR 1,500 per year", "Flexible working hours", "Public transport ticket"],
    team: "A data science group of seven inside a 60-person company, based in Munich.",
    company: "Kestrel",
    companySize: "51-200",
    description:
      "Kestrel helps subscription businesses understand their customers. You'll build the models behind personalization features.",
    experienceLevel: "Mid",
    id: "4",
    industry: "Analytics",
    jobType: "Full-time",
    location: "Munich, DE",
    matchPercent: 81,
    niceToHave: ["Experience with experimentation platforms", "SQL performance tuning"],
    posted: "3 days ago",
    requirements: [
      "Strong SQL and comfort working directly with large datasets",
      "Experience designing and analyzing A/B tests",
      "Ability to communicate findings clearly to product teams",
    ],
    responsibilities: [
      "Build and maintain personalization and segmentation models",
      "Design experiments to validate new features",
      "Partner with product to translate findings into roadmap decisions",
    ],
    salaryMax: 82000,
    salaryMin: 62000,
    sponsorsVisa: false,
    tags: ["SQL", "Experimentation", "Python", "Statistics"],
    title: "Data Scientist, Personalization",
    workMode: "Hybrid",
  },
  {
    about: "Alpenwerk builds internal software for manufacturing plants across the DACH region.",
    applyInDays: 28,
    benefits: ["Remote-first with a co-working allowance", "Home-office budget", "28 days of paid leave", "Company pension contribution"],
    team: "A six-person full-stack team that works directly with plant operations staff.",
    company: "Alpenwerk",
    companySize: "1-50",
    description:
      "Alpenwerk is a small full-stack team building internal tooling for manufacturing operations across the DACH region.",
    experienceLevel: "Mid",
    id: "5",
    industry: "Manufacturing",
    jobType: "Full-time",
    location: "Zurich, CH",
    matchPercent: 78,
    niceToHave: ["Experience in a regulated or industrial environment", "German language skills"],
    posted: "2 days ago",
    requirements: [
      "Solid experience across React and Node.js in production",
      "Comfortable working directly with operations stakeholders",
      "Ability to work independently in a small team",
    ],
    responsibilities: [
      "Build and maintain internal tools used on the factory floor",
      "Work directly with operations staff to scope new features",
      "Own features from design through deployment",
    ],
    salaryMax: 105000,
    salaryMin: 85000,
    sponsorsVisa: true,
    tags: ["React", "Node", "TypeScript", "PostgreSQL"],
    title: "Full-Stack Engineer",
    workMode: "On-site",
  },
  {
    about: "Loopwork builds productivity software for distributed teams.",
    applyInDays: 12,
    benefits: ["Hybrid schedule", "Learning budget", "Health and wellbeing allowance", "Team offsites twice a year"],
    team: "A design pod of three embedded with the editor engineering team.",
    company: "Loopwork",
    companySize: "51-200",
    description:
      "Loopwork builds productivity software for distributed teams. This role focuses on the collaborative editing experience.",
    experienceLevel: "Mid",
    id: "6",
    industry: "Software",
    jobType: "Part-time",
    location: "Remote, EU",
    matchPercent: 80,
    niceToHave: ["Experience with real-time collaboration tools", "Accessibility experience"],
    posted: "5 days ago",
    requirements: [
      "Strong interaction-design skills with a systems mindset",
      "Comfort prototyping in code, not just static mockups",
      "Experience shipping design-system-backed products",
    ],
    responsibilities: [
      "Design the core collaborative editing experience",
      "Prototype and validate interaction patterns with users",
      "Work closely with a small, senior engineering team",
    ],
    salaryMax: 75000,
    salaryMin: 55000,
    sponsorsVisa: false,
    tags: ["UI Design", "Interaction Design", "Design systems", "Figma"],
    title: "UI/UX Designer",
    workMode: "Remote",
  },
];

// Additional fictional listings, generated from compact seeds so the list
// feels realistic (filters, pagination, "+N" tags) without hand-writing each.
const generatedJobs: MockJob[] = [
  {
    about: "Brightwave builds customer-facing analytics dashboards for retailers.",
    applyInDays: 8,
    benefits: ["30 days of paid leave", "Learning budget of EUR 1,500 per year", "Flexible working hours", "Public transport ticket"],
    company: "Brightwave",
    companySize: "51-200",
    description: "Brightwave builds customer-facing analytics dashboards for retailers. We are hiring a Frontend Engineer to build fast, accessible interfaces for the analytics product.",
    experienceLevel: "Mid",
    id: "7",
    industry: "Software",
    jobType: "Full-time",
    location: "Hamburg, DE",
    matchPercent: 84,
    niceToHave: ["Experience with Testing", "Comfort working in a small, fast-moving team"],
    posted: "a day ago",
    requirements: ["3+ years of relevant experience, including React", "Working knowledge of TypeScript and Accessibility", "Clear, collaborative communication with designers and backend engineers"],
    responsibilities: ["Own the component library and page performance", "Work day to day with designers and backend engineers", "Use Accessibility to raise quality and speed"],
    salaryMax: 80000,
    salaryMin: 62000,
    sponsorsVisa: true,
    tags: ["React", "TypeScript", "Accessibility", "Testing"],
    team: "You will work with designers and backend engineers in a team of 4 to 6 people.",
    title: "Frontend Engineer",
    workMode: "Hybrid",
  },
  {
    about: "Northlight develops workflow software for hospital logistics teams.",
    applyInDays: 11,
    benefits: ["Remote-first with a co-working allowance", "Home-office budget", "28 days of paid leave", "Company pension contribution"],
    company: "Northlight",
    companySize: "201-1000",
    description: "Northlight develops workflow software for hospital logistics teams. We are hiring a Senior Product Manager to set direction for the scheduling product and ship it with engineering.",
    experienceLevel: "Senior",
    id: "8",
    industry: "Software",
    jobType: "Full-time",
    location: "Berlin, DE",
    matchPercent: 79,
    niceToHave: ["Experience with Experimentation", "Comfort working in a small, fast-moving team"],
    posted: "2 days ago",
    requirements: ["5+ years of relevant experience, including Roadmapping", "Working knowledge of Analytics and Stakeholder management", "Clear, collaborative communication with engineering, design and clinical operations"],
    responsibilities: ["Own the roadmap and success metrics", "Work day to day with engineering, design and clinical operations", "Use Stakeholder management to raise quality and speed"],
    salaryMax: 110000,
    salaryMin: 85000,
    sponsorsVisa: false,
    tags: ["Roadmapping", "Analytics", "Stakeholder management", "Experimentation"],
    team: "You will work with engineering, design and clinical operations in a team of 5 to 7 people.",
    title: "Senior Product Manager",
    workMode: "Hybrid",
  },
  {
    about: "Kite Analytics turns raw financial data into reports for asset managers.",
    applyInDays: 14,
    benefits: ["Hybrid schedule", "Learning budget", "Health and wellbeing allowance", "Team offsites twice a year"],
    company: "Kite Analytics",
    companySize: "51-200",
    description: "Kite Analytics turns raw financial data into reports for asset managers. We are hiring a Data Analyst to answer business questions with clean, reliable analysis.",
    experienceLevel: "Entry",
    id: "9",
    industry: "Analytics",
    jobType: "Full-time",
    location: "Frankfurt, DE",
    matchPercent: 72,
    niceToHave: ["Experience with Statistics", "Comfort working in a small, fast-moving team"],
    posted: "4 days ago",
    requirements: ["1+ years of relevant experience, including SQL", "Working knowledge of Python and Tableau", "Clear, collaborative communication with account managers and data engineers"],
    responsibilities: ["Own weekly reporting and ad-hoc analyses", "Work day to day with account managers and data engineers", "Use Tableau to raise quality and speed"],
    salaryMax: 60000,
    salaryMin: 48000,
    sponsorsVisa: true,
    tags: ["SQL", "Python", "Tableau", "Statistics"],
    team: "You will work with account managers and data engineers in a team of 6 to 8 people.",
    title: "Data Analyst",
    workMode: "On-site",
  },
  {
    about: "Helioform designs robotic cells for precision assembly lines.",
    applyInDays: 17,
    benefits: ["Relocation support", "30 days of paid leave", "Modern equipment of your choice", "Language course budget"],
    company: "Helioform",
    companySize: "51-200",
    description: "Helioform designs robotic cells for precision assembly lines. We are hiring a Robotics Software Engineer to develop the control software behind our robotic cells.",
    experienceLevel: "Senior",
    id: "10",
    industry: "Manufacturing",
    jobType: "Full-time",
    location: "Munich, DE",
    matchPercent: 74,
    niceToHave: ["Experience with Computer vision", "Comfort working in a small, fast-moving team"],
    posted: "3 days ago",
    requirements: ["5+ years of relevant experience, including C++", "Working knowledge of ROS and Python", "Clear, collaborative communication with mechanical and electrical engineers"],
    responsibilities: ["Own motion planning and vision pipelines", "Work day to day with mechanical and electrical engineers", "Use Python to raise quality and speed"],
    salaryMax: 115000,
    salaryMin: 90000,
    sponsorsVisa: false,
    tags: ["C++", "ROS", "Python", "Computer vision"],
    team: "You will work with mechanical and electrical engineers in a team of 7 to 9 people.",
    title: "Robotics Software Engineer",
    workMode: "On-site",
  },
  {
    about: "Cobaltine Health makes patient-facing apps for chronic-condition care.",
    applyInDays: 20,
    benefits: ["30 days of paid leave", "Learning budget of EUR 1,500 per year", "Flexible working hours", "Public transport ticket"],
    company: "Cobaltine Health",
    companySize: "51-200",
    description: "Cobaltine Health makes patient-facing apps for chronic-condition care. We are hiring a UX Researcher to run research that shapes how patients use the app.",
    experienceLevel: "Mid",
    id: "11",
    industry: "Healthcare",
    jobType: "Full-time",
    location: "Remote, EU",
    matchPercent: 83,
    niceToHave: ["Experience with Accessibility", "Comfort working in a small, fast-moving team"],
    posted: "5 days ago",
    requirements: ["3+ years of relevant experience, including User research", "Working knowledge of Interviewing and Figma", "Clear, collaborative communication with designers, product managers and clinicians"],
    responsibilities: ["Own the research plan and insight sharing", "Work day to day with designers, product managers and clinicians", "Use Figma to raise quality and speed"],
    salaryMax: 78000,
    salaryMin: 64000,
    sponsorsVisa: true,
    tags: ["User research", "Interviewing", "Figma", "Accessibility"],
    team: "You will work with designers, product managers and clinicians in a team of 8 to 10 people.",
    title: "UX Researcher",
    workMode: "Remote",
  },
  {
    about: "Lumengrid operates software for smart metering across Germany.",
    applyInDays: 23,
    benefits: ["Remote-first with a co-working allowance", "Home-office budget", "28 days of paid leave", "Company pension contribution"],
    company: "Lumengrid",
    companySize: "51-200",
    description: "Lumengrid operates software for smart metering across Germany. We are hiring a DevOps Engineer to keep our platform reliable and easy to deploy.",
    experienceLevel: "Mid",
    id: "12",
    industry: "Energy",
    jobType: "Full-time",
    location: "Leipzig, DE",
    matchPercent: 71,
    niceToHave: ["Experience with Observability", "Comfort working in a small, fast-moving team"],
    posted: "6 days ago",
    requirements: ["3+ years of relevant experience, including Kubernetes", "Working knowledge of Terraform and AWS", "Clear, collaborative communication with backend engineers and security"],
    responsibilities: ["Own infrastructure as code and incident response", "Work day to day with backend engineers and security", "Use AWS to raise quality and speed"],
    salaryMax: 86000,
    salaryMin: 68000,
    sponsorsVisa: false,
    tags: ["Kubernetes", "Terraform", "AWS", "Observability"],
    team: "You will work with backend engineers and security in a team of 9 to 11 people.",
    title: "DevOps Engineer",
    workMode: "Hybrid",
  },
  {
    about: "Ostwind sells scheduling software to small hospitality businesses.",
    applyInDays: 26,
    benefits: ["Hybrid schedule", "Learning budget", "Health and wellbeing allowance", "Team offsites twice a year"],
    company: "Ostwind",
    companySize: "1-50",
    description: "Ostwind sells scheduling software to small hospitality businesses. We are hiring a Marketing Manager to grow qualified signups through content and lifecycle campaigns.",
    experienceLevel: "Mid",
    id: "13",
    industry: "Software",
    jobType: "Full-time",
    location: "Cologne, DE",
    matchPercent: 66,
    niceToHave: ["Experience with Campaigns", "Comfort working in a small, fast-moving team"],
    posted: "2 days ago",
    requirements: ["3+ years of relevant experience, including Content strategy", "Working knowledge of SEO and Analytics", "Clear, collaborative communication with sales and product marketing"],
    responsibilities: ["Own the acquisition funnel and content calendar", "Work day to day with sales and product marketing", "Use Analytics to raise quality and speed"],
    salaryMax: 72000,
    salaryMin: 58000,
    sponsorsVisa: true,
    tags: ["Content strategy", "SEO", "Analytics", "Campaigns"],
    team: "You will work with sales and product marketing in a team of 4 to 12 people.",
    title: "Marketing Manager",
    workMode: "Hybrid",
  },
  {
    about: "Marlowe Finance provides payment infrastructure for mid-sized banks.",
    applyInDays: 29,
    benefits: ["Relocation support", "30 days of paid leave", "Modern equipment of your choice", "Language course budget"],
    company: "Marlowe Finance",
    companySize: "201-1000",
    description: "Marlowe Finance provides payment infrastructure for mid-sized banks. We are hiring a Backend Engineer to build reliable services that move money safely.",
    experienceLevel: "Mid",
    id: "14",
    industry: "Finance",
    jobType: "Full-time",
    location: "Frankfurt, DE",
    matchPercent: 69,
    niceToHave: ["Experience with Distributed systems", "Comfort working in a small, fast-moving team"],
    posted: "a week ago",
    requirements: ["3+ years of relevant experience, including Java", "Working knowledge of PostgreSQL and Kafka", "Clear, collaborative communication with compliance and platform teams"],
    responsibilities: ["Own the payments ledger service", "Work day to day with compliance and platform teams", "Use Kafka to raise quality and speed"],
    salaryMax: 98000,
    salaryMin: 76000,
    sponsorsVisa: false,
    tags: ["Java", "PostgreSQL", "Kafka", "Distributed systems"],
    team: "You will work with compliance and platform teams in a team of 5 to 13 people.",
    title: "Backend Engineer",
    workMode: "Hybrid",
  },
  {
    about: "Pixelhaus is a small studio producing product films for tech companies.",
    applyInDays: 10,
    benefits: ["30 days of paid leave", "Learning budget of EUR 1,500 per year", "Flexible working hours", "Public transport ticket"],
    company: "Pixelhaus",
    companySize: "1-50",
    description: "Pixelhaus is a small studio producing product films for tech companies. We are hiring a Motion Designer to craft motion and explainer content for client launches.",
    experienceLevel: "Mid",
    id: "15",
    industry: "Media",
    jobType: "Contract",
    location: "Berlin, DE",
    matchPercent: 77,
    niceToHave: ["Experience with Brand design", "Comfort working in a small, fast-moving team"],
    posted: "3 days ago",
    requirements: ["3+ years of relevant experience, including After Effects", "Working knowledge of Figma and Storyboarding", "Clear, collaborative communication with producers and copywriters"],
    responsibilities: ["Own storyboards through final delivery", "Work day to day with producers and copywriters", "Use Storyboarding to raise quality and speed"],
    salaryMax: 70000,
    salaryMin: 55000,
    sponsorsVisa: true,
    tags: ["After Effects", "Figma", "Storyboarding", "Brand design"],
    team: "You will work with producers and copywriters in a team of 6 to 14 people.",
    title: "Motion Designer",
    workMode: "Remote",
  },
  {
    about: "Tandemline coordinates last-mile deliveries for online retailers.",
    applyInDays: 13,
    benefits: ["Remote-first with a co-working allowance", "Home-office budget", "28 days of paid leave", "Company pension contribution"],
    company: "Tandemline",
    companySize: "201-1000",
    description: "Tandemline coordinates last-mile deliveries for online retailers. We are hiring a Operations Analyst to find and fix bottlenecks in delivery operations.",
    experienceLevel: "Entry",
    id: "16",
    industry: "Logistics",
    jobType: "Full-time",
    location: "Hamburg, DE",
    matchPercent: 63,
    niceToHave: ["Experience with Reporting", "Comfort working in a small, fast-moving team"],
    posted: "4 days ago",
    requirements: ["1+ years of relevant experience, including Excel", "Working knowledge of SQL and Process improvement", "Clear, collaborative communication with depot managers and planners"],
    responsibilities: ["Own daily KPI reporting and root-cause reviews", "Work day to day with depot managers and planners", "Use Process improvement to raise quality and speed"],
    salaryMax: 58000,
    salaryMin: 46000,
    sponsorsVisa: false,
    tags: ["Excel", "SQL", "Process improvement", "Reporting"],
    team: "You will work with depot managers and planners in a team of 7 to 6 people.",
    title: "Operations Analyst",
    workMode: "On-site",
  },
  {
    about: "Quartzo Labs builds document-understanding models for insurers.",
    applyInDays: 16,
    benefits: ["Hybrid schedule", "Learning budget", "Health and wellbeing allowance", "Team offsites twice a year"],
    company: "Quartzo Labs",
    companySize: "1-50",
    description: "Quartzo Labs builds document-understanding models for insurers. We are hiring a Machine Learning Engineer to take models from research to production.",
    experienceLevel: "Senior",
    id: "17",
    industry: "Software",
    jobType: "Full-time",
    location: "Vienna, AT",
    matchPercent: 81,
    niceToHave: ["Experience with SQL", "Comfort working in a small, fast-moving team"],
    posted: "2 days ago",
    requirements: ["5+ years of relevant experience, including Python", "Working knowledge of PyTorch and MLOps", "Clear, collaborative communication with research scientists and backend engineers"],
    responsibilities: ["Own training pipelines and evaluation", "Work day to day with research scientists and backend engineers", "Use MLOps to raise quality and speed"],
    salaryMax: 105000,
    salaryMin: 82000,
    sponsorsVisa: true,
    tags: ["Python", "PyTorch", "MLOps", "SQL"],
    team: "You will work with research scientists and backend engineers in a team of 8 to 7 people.",
    title: "Machine Learning Engineer",
    workMode: "Hybrid",
  },
  {
    about: "Verdant Mobility develops apps for electric-vehicle charging and fleet management.",
    applyInDays: 19,
    benefits: ["Relocation support", "30 days of paid leave", "Modern equipment of your choice", "Language course budget"],
    company: "Verdant Mobility",
    companySize: "201-1000",
    description: "Verdant Mobility develops apps for electric-vehicle charging and fleet management. We are hiring a Product Designer to design charging and trip-planning experiences drivers trust.",
    experienceLevel: "Mid",
    id: "18",
    industry: "Automotive",
    jobType: "Full-time",
    location: "Stuttgart, DE",
    matchPercent: 80,
    niceToHave: ["Experience with User research", "Comfort working in a small, fast-moving team"],
    posted: "5 days ago",
    requirements: ["3+ years of relevant experience, including Figma", "Working knowledge of Design systems and Prototyping", "Clear, collaborative communication with product managers and mobile engineers"],
    responsibilities: ["Own the design system and key flows", "Work day to day with product managers and mobile engineers", "Use Prototyping to raise quality and speed"],
    salaryMax: 84000,
    salaryMin: 66000,
    sponsorsVisa: false,
    tags: ["Figma", "Design systems", "Prototyping", "User research"],
    team: "You will work with product managers and mobile engineers in a team of 9 to 8 people.",
    title: "Product Designer",
    workMode: "Hybrid",
  },
  {
    about: "Skyloft Cloud sells cloud infrastructure services to enterprises.",
    applyInDays: 22,
    benefits: ["30 days of paid leave", "Learning budget of EUR 1,500 per year", "Flexible working hours", "Public transport ticket"],
    company: "Skyloft Cloud",
    companySize: "1000+",
    description: "Skyloft Cloud sells cloud infrastructure services to enterprises. We are hiring a Solutions Architect to design cloud solutions with customers and guide adoption.",
    experienceLevel: "Senior",
    id: "19",
    industry: "Software",
    jobType: "Full-time",
    location: "Berlin, DE",
    matchPercent: 68,
    niceToHave: ["Experience with Stakeholder management", "Comfort working in a small, fast-moving team"],
    posted: "a week ago",
    requirements: ["5+ years of relevant experience, including AWS", "Working knowledge of Architecture and Kubernetes", "Clear, collaborative communication with account executives and customer engineers"],
    responsibilities: ["Own technical discovery and reference architectures", "Work day to day with account executives and customer engineers", "Use Kubernetes to raise quality and speed"],
    salaryMax: 125000,
    salaryMin: 95000,
    sponsorsVisa: true,
    tags: ["AWS", "Architecture", "Kubernetes", "Stakeholder management"],
    team: "You will work with account executives and customer engineers in a team of 4 to 9 people.",
    title: "Solutions Architect",
    workMode: "Hybrid",
  },
  {
    about: "Bayfield Media publishes newsletters and guides for early-career professionals.",
    applyInDays: 25,
    benefits: ["Remote-first with a co-working allowance", "Home-office budget", "28 days of paid leave", "Company pension contribution"],
    company: "Bayfield Media",
    companySize: "51-200",
    description: "Bayfield Media publishes newsletters and guides for early-career professionals. We are hiring a Content Editor to edit and shape clear, useful career content.",
    experienceLevel: "Entry",
    id: "20",
    industry: "Media",
    jobType: "Part-time",
    location: "Remote, EU",
    matchPercent: 64,
    niceToHave: ["Experience with Editing", "Comfort working in a small, fast-moving team"],
    posted: "3 days ago",
    requirements: ["1+ years of relevant experience, including Copywriting", "Working knowledge of SEO and CMS", "Clear, collaborative communication with freelance writers and the audience team"],
    responsibilities: ["Own the editorial calendar and quality standards", "Work day to day with freelance writers and the audience team", "Use CMS to raise quality and speed"],
    salaryMax: 42000,
    salaryMin: 32000,
    sponsorsVisa: false,
    tags: ["Copywriting", "SEO", "CMS", "Editing"],
    team: "You will work with freelance writers and the audience team in a team of 5 to 10 people.",
    title: "Content Editor",
    workMode: "Remote",
  },
  {
    about: "Rivenstone builds contract-review software for in-house legal teams.",
    applyInDays: 28,
    benefits: ["Hybrid schedule", "Learning budget", "Health and wellbeing allowance", "Team offsites twice a year"],
    company: "Rivenstone",
    companySize: "51-200",
    description: "Rivenstone builds contract-review software for in-house legal teams. We are hiring a Legal Operations Specialist to streamline how legal teams draft, review and track contracts.",
    experienceLevel: "Mid",
    id: "21",
    industry: "Legal tech",
    jobType: "Full-time",
    location: "Duesseldorf, DE",
    matchPercent: 59,
    niceToHave: ["Experience with Compliance", "Comfort working in a small, fast-moving team"],
    posted: "6 days ago",
    requirements: ["3+ years of relevant experience, including Contract management", "Working knowledge of Process design and Excel", "Clear, collaborative communication with lawyers and product engineers"],
    responsibilities: ["Own internal tooling requirements and playbooks", "Work day to day with lawyers and product engineers", "Use Excel to raise quality and speed"],
    salaryMax: 70000,
    salaryMin: 56000,
    sponsorsVisa: true,
    tags: ["Contract management", "Process design", "Excel", "Compliance"],
    team: "You will work with lawyers and product engineers in a team of 6 to 11 people.",
    title: "Legal Operations Specialist",
    workMode: "Hybrid",
  },
  {
    about: "Solvara makes energy-trading software used by utilities.",
    applyInDays: 9,
    benefits: ["Relocation support", "30 days of paid leave", "Modern equipment of your choice", "Language course budget"],
    company: "Solvara",
    companySize: "51-200",
    description: "Solvara makes energy-trading software used by utilities. We are hiring a QA Engineer to raise confidence in every release through solid automation.",
    experienceLevel: "Mid",
    id: "22",
    industry: "Software",
    jobType: "Full-time",
    location: "Leipzig, DE",
    matchPercent: 70,
    niceToHave: ["Experience with CI/CD", "Comfort working in a small, fast-moving team"],
    posted: "2 days ago",
    requirements: ["3+ years of relevant experience, including Test automation", "Working knowledge of TypeScript and Cypress", "Clear, collaborative communication with developers and product owners"],
    responsibilities: ["Own the end-to-end test suite and release checks", "Work day to day with developers and product owners", "Use Cypress to raise quality and speed"],
    salaryMax: 72000,
    salaryMin: 58000,
    sponsorsVisa: false,
    tags: ["Test automation", "TypeScript", "Cypress", "CI/CD"],
    team: "You will work with developers and product owners in a team of 7 to 12 people.",
    title: "QA Engineer",
    workMode: "Remote",
  },
  {
    about: "Zephyrline supplies maintenance planning software to regional airlines.",
    applyInDays: 12,
    benefits: ["30 days of paid leave", "Learning budget of EUR 1,500 per year", "Flexible working hours", "Public transport ticket"],
    company: "Zephyrline",
    companySize: "201-1000",
    description: "Zephyrline supplies maintenance planning software to regional airlines. We are hiring a Customer Success Manager to help airline customers get lasting value from the product.",
    experienceLevel: "Mid",
    id: "23",
    industry: "Aviation",
    jobType: "Full-time",
    location: "Munich, DE",
    matchPercent: 62,
    niceToHave: ["Experience with Analytics", "Comfort working in a small, fast-moving team"],
    posted: "a week ago",
    requirements: ["3+ years of relevant experience, including Customer onboarding", "Working knowledge of CRM and Communication", "Clear, collaborative communication with sales and support engineers"],
    responsibilities: ["Own onboarding plans and renewal health", "Work day to day with sales and support engineers", "Use Communication to raise quality and speed"],
    salaryMax: 76000,
    salaryMin: 60000,
    sponsorsVisa: true,
    tags: ["Customer onboarding", "CRM", "Communication", "Analytics"],
    team: "You will work with sales and support engineers in a team of 8 to 13 people.",
    title: "Customer Success Manager",
    workMode: "Hybrid",
  },
  {
    about: "Nimbly runs analytics platforms for e-commerce brands.",
    applyInDays: 15,
    benefits: ["Remote-first with a co-working allowance", "Home-office budget", "28 days of paid leave", "Company pension contribution"],
    company: "Nimbly",
    companySize: "1-50",
    description: "Nimbly runs analytics platforms for e-commerce brands. We are hiring a Data Engineer to design reliable data pipelines for reporting and ML.",
    experienceLevel: "Senior",
    id: "24",
    industry: "Analytics",
    jobType: "Contract",
    location: "Remote, EU",
    matchPercent: 75,
    niceToHave: ["Experience with SQL", "Comfort working in a small, fast-moving team"],
    posted: "4 days ago",
    requirements: ["5+ years of relevant experience, including Python", "Working knowledge of dbt and Airflow", "Clear, collaborative communication with analysts and data scientists"],
    responsibilities: ["Own warehouse models and orchestration", "Work day to day with analysts and data scientists", "Use Airflow to raise quality and speed"],
    salaryMax: 100000,
    salaryMin: 78000,
    sponsorsVisa: false,
    tags: ["Python", "dbt", "Airflow", "SQL"],
    team: "You will work with analysts and data scientists in a team of 9 to 14 people.",
    title: "Data Engineer",
    workMode: "Remote",
  },
];

export const mockJobs: MockJob[] = [...featuredJobs, ...generatedJobs];

// Shared by JobsPage's location filter/select and Overview's location filter,
// so both read the exact same list instead of each deriving it separately.
export const allJobLocations = Array.from(new Set(mockJobs.map((job) => job.location))).sort((a, b) =>
  a.localeCompare(b),
);
