-- Storage and security boundary for the server-side ATS ingestion worker.

create table public.job_companies (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 255),
  normalized_name text not null check (char_length(normalized_name) between 1 and 255),
  domain text unique,
  created_at timestamptz not null default now()
);

create index job_companies_normalized_name_idx
  on public.job_companies (normalized_name);

create table public.job_boards (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.job_companies (id) on delete cascade,
  key text not null unique check (char_length(key) between 1 and 255),
  company_name text not null check (char_length(company_name) between 1 and 255),
  source_type text not null check (source_type in ('ats', 'generic', 'fixture')),
  provider text,
  url text,
  enabled boolean not null default true,
  last_run_at timestamptz,
  last_success_at timestamptz,
  last_http_status integer check (last_http_status between 100 and 599),
  last_jobs_found integer not null default 0 check (last_jobs_found >= 0),
  last_error text
);

create index job_boards_company_id_idx on public.job_boards (company_id);
create index job_boards_provider_enabled_idx on public.job_boards (provider, enabled);

create table public.jobs (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.job_companies (id) on delete cascade,
  fingerprint text not null unique check (char_length(fingerprint) = 64),
  title text not null check (char_length(title) between 1 and 500),
  normalized_title text not null check (char_length(normalized_title) between 1 and 500),
  description text not null default '',
  location_text text not null default '' check (char_length(location_text) <= 500),
  city text,
  state text,
  country text,
  remote_type text,
  employment_type text,
  salary_min double precision,
  salary_max double precision,
  salary_currency text,
  posted_at timestamptz,
  expires_at timestamptz,
  apply_url text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  constraint jobs_salary_range_check check (
    salary_min is null or salary_max is null or salary_min <= salary_max
  )
);

create index jobs_company_id_idx on public.jobs (company_id);
create index jobs_active_recent_idx on public.jobs (last_seen_at desc) where status = 'active';
create index jobs_country_city_idx on public.jobs (country, city) where status = 'active';
create index jobs_remote_type_idx on public.jobs (remote_type) where status = 'active';
create index jobs_normalized_title_idx on public.jobs (normalized_title);

create table public.job_sources (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs (id) on delete cascade,
  source_id bigint not null references public.job_boards (id) on delete cascade,
  source_job_id text not null,
  source_url text not null,
  raw_data jsonb not null default '{}'::jsonb,
  retrieved_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (source_id, source_job_id)
);

create index job_sources_job_id_idx on public.job_sources (job_id);
create index job_sources_source_id_idx on public.job_sources (source_id);

create table public.job_ingestion_runs (
  id bigint generated by default as identity primary key,
  provider text not null default 'mixed',
  status text not null default 'running' check (
    status in ('running', 'completed', 'completed_with_errors', 'failed')
  ),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  sources_attempted integer not null default 0 check (sources_attempted >= 0),
  raw_jobs integer not null default 0 check (raw_jobs >= 0),
  new_jobs integer not null default 0 check (new_jobs >= 0),
  duplicates integer not null default 0 check (duplicates >= 0),
  failed_sources integer not null default 0 check (failed_sources >= 0),
  error text
);

create index job_ingestion_runs_provider_started_idx
  on public.job_ingestion_runs (provider, started_at desc);

create table public.job_skills_catalog (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(name) between 1 and 120)
);

create table public.job_skill_links (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs (id) on delete cascade,
  skill_id bigint not null references public.job_skills_catalog (id) on delete cascade,
  unique (job_id, skill_id)
);

create table public.job_raw_snapshots (
  id bigint generated by default as identity primary key,
  source_url text not null,
  content_hash text not null unique check (char_length(content_hash) = 64),
  raw_content text not null,
  retrieved_at timestamptz not null default now()
);

create index job_raw_snapshots_source_url_idx
  on public.job_raw_snapshots (source_url);

alter table public.job_companies enable row level security;
alter table public.job_boards enable row level security;
alter table public.jobs enable row level security;
alter table public.job_sources enable row level security;
alter table public.job_ingestion_runs enable row level security;
alter table public.job_skills_catalog enable row level security;
alter table public.job_skill_links enable row level security;
alter table public.job_raw_snapshots enable row level security;

revoke all on table public.job_companies from anon, authenticated;
revoke all on table public.job_boards from anon, authenticated;
revoke all on table public.jobs from anon, authenticated;
revoke all on table public.job_sources from anon, authenticated;
revoke all on table public.job_ingestion_runs from anon, authenticated;
revoke all on table public.job_skills_catalog from anon, authenticated;
revoke all on table public.job_skill_links from anon, authenticated;
revoke all on table public.job_raw_snapshots from anon, authenticated;

grant select on table public.job_companies to authenticated;
grant select on table public.jobs to authenticated;
grant all on table public.job_companies to service_role;
grant all on table public.job_boards to service_role;
grant all on table public.jobs to service_role;
grant all on table public.job_sources to service_role;
grant all on table public.job_ingestion_runs to service_role;
grant all on table public.job_skills_catalog to service_role;
grant all on table public.job_skill_links to service_role;
grant all on table public.job_raw_snapshots to service_role;
grant usage, select on sequence public.job_companies_id_seq to service_role;
grant usage, select on sequence public.job_boards_id_seq to service_role;
grant usage, select on sequence public.jobs_id_seq to service_role;
grant usage, select on sequence public.job_sources_id_seq to service_role;
grant usage, select on sequence public.job_ingestion_runs_id_seq to service_role;
grant usage, select on sequence public.job_skills_catalog_id_seq to service_role;
grant usage, select on sequence public.job_skill_links_id_seq to service_role;
grant usage, select on sequence public.job_raw_snapshots_id_seq to service_role;

create policy "Signed-in users can read job companies"
on public.job_companies
for select
to authenticated
using (true);

create policy "Signed-in users can read active jobs"
on public.jobs
for select
to authenticated
using (status = 'active');

comment on table public.job_sources is
  'Private ATS source occurrences and raw provider payloads; server-side access only.';
comment on table public.job_ingestion_runs is
  'Private operational diagnostics for the ATS ingestion worker.';
comment on table public.job_raw_snapshots is
  'Optional private source snapshots; no browser access.';
